UNICODE_FRACTIONS = {
    "¼": "1/4",
    "½": "1/2",
    "¾": "3/4",
    "⅓": "1/3",
    "⅔": "2/3",
    "⅛": "1/8",
    "⅜": "3/8",
    "⅝": "5/8",
    "⅞": "7/8",
}


UNIT_ALIASES = {
    "teaspoon": "tsp",
    "teaspoons": "tsp",
    "tablespoon": "tbsp",
    "tablespoons": "tbsp",
    "gram": "g",
    "grams": "g",
    "kilogram": "kg",
    "kilograms": "kg",
    "milligram": "mg",
    "milligrams": "mg",
    "milliliter": "ml",
    "milliliters": "ml",
    "liter": "l",
    "liters": "l",
    "ounce": "oz",
    "ounces": "oz",
    "pound": "lb",
    "pounds": "lb",
    "cups": "cup",
    "fillets": "fillet",
    "carrots": "carrot",
    "cubes": "cube",
    "packs": "pack",
    "packets": "packet",
    "tins": "tin",
    "cans": "can",
}

SOURCE_UNITS = {
    "g",
    "kg",
    "mg",
    "ml",
    "l",
    "oz",
    "lb",
    "tsp",
    "tbsp",
    "cup",
    "cups",
    "pack",
    "packet",
    "tin",
    "can",
    "fillet",
    "fillets",
    "cube",
    "cubes",
}

UNIT_TO_BASE = {
    "tsp": ("volume", 1),
    "tbsp": ("volume", 3),
    "cup": ("volume", 48),
    "ml": ("volume_ml", 1),
    "l": ("volume_ml", 1000),
    "mg": ("weight_g", 0.001),
    "g": ("weight_g", 1),
    "kg": ("weight_g", 1000),
    "oz": ("weight_oz", 1),
    "lb": ("weight_oz", 16),
}

KNOWN_EXPLICIT_UNITS = {
    "tsp",
    "tbsp",
    "cup",
    "g",
    "kg",
    "mg",
    "ml",
    "l",
    "oz",
    "lb",
}